#!/bin/bash
set -e

replace_core=false

for arg in "$@"; do
  if [ "$arg" == "--replace-core" ]; then
    replace_core=true
    break
  fi
done

if [ $# -ge 3 -a $1 == "compile" -a $replace_core == true ]; then
  echo "Replacing Dataform core in project directory..."
  bazel build packages/@dataform/core:bundle.js && \
    cp bazel-bin/packages/@dataform/core/bundle.js $2/node_modules/@dataform/core/
  echo "Dataform core successfully replaced in project directory"
fi

bazel build //packages/@dataform/cli:bin
./bazel-bin/packages/@dataform/cli/bin.sh "$@"
